### ISSUE TITLE
Knative gen-api-reference-docs.sh fail for knative/serving api v0.8

### ISSUE THREAD

**Issue by RichieEscarez** [ahmetb/gen-crd-api-reference-docs#10]
Error:
`F0807 13:58:20.621526  168834 main.go:444] type invalid type has kind=Unsupported which is unhandled
`

Command run:
`KNATIVE_EVENTING_COMMIT=v0.8.0 KNATIVE_EVENTING_RESOURCES_COMMIT=v0.8.0 KNATIVE_SERVING_COMMIT=v0.8.0 ./gen-api-reference-docs.sh`

Note that Knative/build has been deprecated and removed from our docs and these API builds (thus no Build version in the command).

Comment:
Running the same command but downgrading only knative/serving version to v0.7.0 runs successfully.

FULL LOG:
```
KNATIVE_EVENTING_COMMIT=v0.8.0 KNATIVE_EVENTING_RESOURCES_COMMIT=v0.8.0 KNATIVE_SERVING_COMMIT=v0.8.0 ./gen-api-reference-docs.sh
go: creating new go.mod: module tmp
go: finding golang.org/x/tools latest
go: finding k8s.io/gengo latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/xerrors latest
go: finding golang.org/x/sys latest
Cloning into '/tmp/tmp.dYdA8Mpez8/src/github.com/knative/serving'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 54814 (delta 7), reused 13 (delta 5), pack-reused 54779
Receiving objects: 100% (54814/54814), 37.93 MiB | 14.72 MiB/s, done.
Resolving deltas: 100% (35670/35670), done.
I0807 14:22:34.076743  176988 main.go:123] parsing go packages in directory ./pkg/apis
W0807 14:22:36.279294  176988 parse.go:239] Ignoring child directory github.com/knative/serving/pkg/apis/config/testdata: No files for pkg "github.com/knative/serving/pkg/apis/config/testdata"
I0807 14:22:36.541306  176988 main.go:225] using package=github.com/knative/serving/pkg/apis/autoscaling/v1alpha1
I0807 14:22:36.541341  176988 main.go:225] using package=github.com/knative/serving/pkg/apis/networking/v1alpha1
I0807 14:22:36.541357  176988 main.go:225] using package=github.com/knative/serving/pkg/apis/serving/v1alpha1
I0807 14:22:36.541369  176988 main.go:225] using package=github.com/knative/serving/pkg/apis/serving/v1beta1
F0807 14:22:36.551807  176988 main.go:444] type invalid type has kind=Unsupported which is unhandled
Cleaning up tmp directory: /tmp/tmp.GusHbFc4ox
Cleaning up tmp directory: /tmp/tmp.dYdA8Mpez8
```

**Comment by ahmetb** [comment]
Do you mind adding a -v=10 flag to the command that calls this tool in the script?

It seems like the tool is claiming there's a Go type called `invalid type` which I highly suspect isn't the cas.

**Comment by RichieEscarez** [comment]
append it to the end, like this: `KNATIVE_EVENTING_COMMIT=v0.8.0 KNATIVE_EVENTING_RESOURCES_COMMIT=v0.8.0 KNATIVE_SERVING_COMMIT=v0.8.0 ./gen-api-reference-docs.sh -v=10`

**Comment by RichieEscarez** [comment]
Same results

**Comment by ahmetb** [comment]
nope not there, to the part inside that .sh script that call this tool.

**Comment by ahmetb** [comment]
right here: https://github.com/knative/docs/blob/9187ee8932e412ccc55902c37c53edfa3cb1191f/hack/gen-api-reference-docs.sh#L110

**Comment by RichieEscarez** [comment]
added
```
....
            -config "${SCRIPTDIR}/reference-docs-gen-config.json" \
            -v=10
```

And it ran a lot longer filling my terminal buffer but still resulted in the same error (final line in the output):
`F0807 15:59:46.832302  213252 main.go:444] type invalid type has kind=Unsupported which is unhandled`

**Comment by ahmetb** [comment]
Yeah that long output could be actually useful so if you run the script with

hack/gen-...sh 2>&1 > out.txt

and attach the out.txt here, it would help.

**Comment by RichieEscarez** [comment]
[out.txt](https://github.com/ahmetb/gen-crd-api-reference-docs/files/3479206/out.txt)

**Comment by RichieEscarez** [comment]
ha, its empty, let me try that again

**Comment by RichieEscarez** [comment]
[out.txt](https://github.com/ahmetb/gen-crd-api-reference-docs/files/3479212/out.txt)

**Comment by RichieEscarez** [comment]
FYI: This is now broken for both v0.9 Serving and Eventing. Same error:
'F0919 09:52:05.470892   19869 main.go:444] type invalid type has kind=Unsupported which is unhandled'

**Comment by abrennan89** [comment]
@ahmetb any updates on the status of this issue?

**Comment by ahmetb** [comment]
It’s in my backlog but it might take a while. This issue is deeper than I originally thought. Knative serving also has hand written api spec now which is a good replacement in the meanwhile.

**Comment by RichieEscarez** [comment]
This was fixed long ago: https://github.com/knative/docs/issues/1661
