### ISSUE TITLE
HTML output produced may be not valid

### ISSUE THREAD

**Issue by squakez** [ahmetb/gen-crd-api-reference-docs#34]
We're experiencing a few problems about HTML validity. Putting below the fragments if they can help you identifying the issue.

* Double `p` included in the resource descriptions. Validator will complain with `No p element in scope but a p end tag seen.`
```
<p>
<p>Package v1alpha1 contains API Schema definitions for the camel v1alpha1 API group</p>
</p>
...
<p>
<p>Kamelet is the Schema for the kamelets API</p>
</p>
```
* `br` tag at the end of `code`. Validator will complain with `End tag br.`
```
<code>apiVersion</code></br>
string</td>
```
* `p` element nested in `h3`. Validator will complain with `Element p not allowed as child of element h3 in this context.`
```
<h3 id="camel.apache.org/v1alpha1.EndpointType">EndpointType
(<code>string</code> alias)</p></h3>
```

**Comment by ahmetb** [comment]
Patches are welcome for these. I am not sure if we have full control over all of them, however. Some of them are probably coming from our "markdown to html" converter, and we have to add `<p>` for the texts that are not detected as paragraph from the package/method godoc comments.
