### ISSUE TITLE
leading spaces removed from ``` sections

### ISSUE THREAD

**Issue by caboteria** [ahmetb/gen-crd-api-reference-docs#52]
Hi! The k8s gateway-api project uses this tool to generate its reference docs. Thank you!

One small problem is that yaml samples (which are included in ``` sections) have their leading spaces stripped somewhere in the process so the output is no longer proper yaml.

Here's the input: https://github.com/kubernetes-sigs/gateway-api/blob/e89bbb7042311703d9e076435ef75f15cf8665c2/apis/v1alpha2/httproute_types.go#L120

Here's the output: https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.HTTPRouteRule

Is there a way to tell gen-crd-api-reference-docs to leave the formatting alone in ``` sections?

Thank you!

**Comment by ahmetb** [comment]
You can check the source code.

**Comment by caboteria** [comment]
OK, will do.
